[package]
name = "testbed_api"
version = "1.0.0"
edition = "2021"

[dependencies]
lambda_runtime = "0.7.0"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
tokio = { version = "1.21.2", features = ["full"] }

[[bin]]
name = "bootstrap"
path = "src/main.rs"