[package]
name = "testbed_api"
version = "1.0.0"
edition = "2021"

[dependencies]
lambda_http = "0.7.0"
serde_json = "1.0.0"
serde = { version = "1.0.0", features = ["derive"] }
tokio = { version = "1.21.2", features = ["full"] }
log = "0.4.14"
simple_logger = "3.0.0"
http = "0.2.5"
reqwest = { version = "0.11.12", features = ["json"] }

[[bin]]
name = "bootstrap"
path = "src/main.rs"