version: "3.7"

services:
  testbed-api:
    image: virtualfinland/testbed-api-builder
    build:
      context: .
      dockerfile: infra/builder.dockerfile
    command: ["sh", "-c", "cargo watch -x 'run --features local-dev'"]
    working_dir: /builder
    volumes:
      - ./:/builder
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
