version: "3.7"

services:
  testbed-api:
    image: virtualfinland/testbed-api-builder:devenv
    build:
      context: .
      dockerfile: infra/builder.dockerfile
      target: devenv
    command: ["sh", "-c", "cargo watch -x 'run --features local-dev'"]
    environment:
      - RUST_BACKTRACE=1
      - LOGGING_LEVEL=debug
    working_dir: /builder
    volumes:
      - ./:/builder
    ports:
      - 3003:3003
    stdin_open: true
    tty: true
