AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: testbed-api local

Resources:
  TestbedAPI:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./build/rust-debug.zip
      Handler: bootstrap
      Runtime: provided.al2
      Timeout: 15
      Architectures:
        - x86_64
      Environment:
        Variables:
          RUST_BACKTRACE: 1
          STAGE: local
          LOGGING_LEVEL: debug
      Events:
        TestbedAPIEvent:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: "/{proxy+}"
            Method: ANY
        TestbedAPIEventRoot:
          Type: HttpApi
          Properties:
            Path: "/"
            Method: ANY
