openapi: 3.0.3
info:
  title: Testbed API
  description: |-
    Testebed API documentation
  version: 1.0.0
paths:
  /:
    get:
      responses:
        "303":
          description: Redirect to swagger docs at /docs
  /health:
    get:
      responses:
        "200":
          description: Health check response
          content:
            text/plain:
              example: "OK"
  /docs:
    get:
      responses:
        "200":
          description: Swagger docs
  /testbed/reverse-proxy:
    post:
      operationId: testbed-reverse-proxy
      requestBody:
        description: The request package
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProxyRequestInput"
      responses:
        "200":
          description: Proxy response
  /testbed/productizers/get-population:
    post:
      operationId: get-population
      requestBody:
        description: The population figure query
        content:
          application/json:
            schema:
              type: object
            examples:
              success:
                summary: JSON example
                value: Loading...
                externalValue: "https://raw.githubusercontent.com/Virtual-Finland/definitions/main/DataProducts/test/lsipii/Figure/Population.json"
      responses:
        "200":
          description: Population figure response
          content:
            application/json:
              schema:
                type: object
              examples:
                success:
                  summary: JSON example
                  value: Loading...
                  externalValue: "https://raw.githubusercontent.com/Virtual-Finland/definitions/main/DataProducts/test/lsipii/Figure/Population.json"
  /testbed/productizers/find-job-postings:
    post:
      operationId: find-job-postings
      requestBody:
        description: The job postings query
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/JobsRequestFromFrontend"
      responses:
        "200":
          description: The job postings
          content:
            application/json:
              schema:
                type: object
              examples:
                success:
                  summary: JSON example
                  value: Loading...
                  externalValue: "https://raw.githubusercontent.com/Virtual-Finland/definitions/main/DataProducts/test/lassipatanen/Job/JobPosting.json"
  /testbed/productizers/user-profile:
    post:
      operationId: user-profile
      requestBody:
        description: The user profile query
        content:
          application/json:
            schema:
              type: object
            examples:
              success:
                summary: JSON example
                value: Loading...
                externalValue: "https://raw.githubusercontent.com/Virtual-Finland/definitions/main/DataProducts/test/lassipatanen/User/Profile.json"
      responses:
        "200":
          description: The user profile response
          content:
            application/json:
              schema:
                type: object
              examples:
                success:
                  summary: JSON example
                  value: Loading...
                  externalValue: "https://raw.githubusercontent.com/Virtual-Finland/definitions/main/DataProducts/test/lassipatanen/User/Profile.json"
components:
  schemas:
    ProxyRequestInput:
      type: object
      properties:
        method:
          type: string
          description: Request method
          example: POST
          enum:
            - GET
            - POST
            - PUT
            - DELETE
        url:
          type: string
          example: https://gateway.testbed.fi/action
        data:
          type: object
        headers:
          type: object
    JobsRequestFromFrontend:
      type: object
      properties:
        query:
          type: string
          description: Search phrase
          example: Chef
        location:
          $ref: "#/components/schemas/RequestLocation"
        occupationCodes:
          type: array
          items:
            type: string
        paging:
          $ref: "#/components/schemas/RequestPagingFromFrontend"
    RequestLocation:
      type: object
      properties:
        countries:
          type: array
          items:
            type: string
        regions:
          type: array
          items:
            type: string
        municipalities:
          type: array
          items:
            type: string
    RequestPagingFromFrontend:
      type: object
      properties:
        itemsPerPage:
          type: number
          example: 20
        pageNumber:
          type: number
          example: 0
