name: Deploy Dev

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    uses: Virtual-Finland-Development/testbed-api/.github/workflows/deployment.yml@main
    secrets: inherit
    with:
      deployment_stage: dev
